# Generated by Django 3.2 on 2022-05-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedido_pedidoplato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoplato',
            name='pedido_id',
            field=models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidoPlatos', to='api.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoplato',
            name='plato_id',
            field=models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidoPlatos', to='api.plato', verbose_name='Plato'),
        ),
    ]
